version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          DOCKER_IMAGE: astrocoders/meteor-s3-backup
          DOCKER_IMAGE_NAME: meteor-s3-backup

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_IMAGE_NAME .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
              docker tag ${DOCKER_IMAGE_NAME} ${DOCKER_IMAGE}
              docker push ${DOCKER_IMAGE}
            fi
